# Generated by Django 5.2.6 on 2025-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('Education', models.CharField(max_length=50)),
                ('Mobile_num', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Guardians_name', models.CharField(max_length=50)),
                ('Guardians_occupation', models.CharField(max_length=50)),
                ('Guardians_number', models.CharField(max_length=50)),
                ('Course', models.CharField(choices=[('PF', 'Python FullStack'), ('DM', 'Digital Marketing'), ('MS', 'Mern Stack')], max_length=50)),
                ('Training', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('Scope_loaction', models.CharField(max_length=50)),
                ('Preferred_timing', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
    ]
