# Generated by Django 5.2.6 on 2025-09-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Scope_loaction',
            new_name='Scope_location',
        ),
    ]
