# Generated by Django 5.2.6 on 2025-11-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_scope_loaction_registration_scope_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Course',
            field=models.CharField(choices=[('PF', 'Python FullStack'), ('DM', ' DigitalMarketing'), ('MS', 'Mern Stack')], max_length=50),
        ),
    ]
